<?php

namespace MyPlaylist\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository
{
}
