<?php

namespace MyPlaylist\AppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SongController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MyPlaylist\AppBundle\Controller\SongController();
        return $instance;
    }
}
