#PARTIE POUR LE HOME
MyPlaylist_home:
    pattern:  /home
    defaults: { _controller: MyPlaylistAppBundle:Home:index }

MyPlaylist_search:
    pattern:   /home/search
    defaults:  { _controller: MyPlaylistAppBundle:Home:search }

MyPlaylist_mail:
    pattern:   /home/mail
    defaults:  { _controller: MyPlaylistAppBundle:Home:mail }

MyPlaylist_about:
    pattern:   /home/about
    defaults:  { _controller: MyPlaylistAppBundle:Home:viewAbout }


#PARTIE POUR LES PLAYLISTS
MyPlaylist_viewPlaylist:
    pattern:   /playlist
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:index }

MyPlaylist_viewPlaylistId:
    pattern:   /playlist/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewPlaylist }
    requirements:
        id:  \d+

MyPlaylist_viewDelPlaylist:
    pattern:   /playlist/del
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewDelPlaylist }

MyPlaylist_viewAddPlaylist:
    pattern:   /playlist/add
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewAdd }  

MyPlaylist_viewEditPlaylist:
    pattern:   /playlist/edit
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewEditPlaylist }

MyPlaylist_editPlaylist:
    pattern:   /playlist/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:editPlaylist }
    requirements:
        id:  \d+

MyPlaylist_view_slugPlaylist:
    pattern:   /playlist/{annee}/{slug}.{format}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewSlug, format: html }
    requirements:
        annee:  \d4
        format: html|xml

#PARTIE POUR LES MUSIQUES
MyPlaylist_viewSong:
    pattern:   /song
    defaults:  { _controller: MyPlaylistAppBundle:Song:index }

MyPlaylist_viewSongId:
    pattern:   /song/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewSong }
    requirements:
        id:  \d+

MyPlaylist_addSongToPlaylist:
    pattern:   /song/{idSong}/addToPlaylist/{idPlaylist}
    defaults:  { _controller: MyPlaylistAppBundle:Song:addToPlaylist }
    requirements:
        idSong:  \d+  
        idPlaylist:  \d+  

MyPlaylist_delSongToPlaylist:
    pattern:   /song/{idSong}/delToPlaylist/{idPlaylist}
    defaults:  { _controller: MyPlaylistAppBundle:Song:delToPlaylist }
    requirements:
        idSong:  \d+  
        idPlaylist:  \d+          

MyPlaylist_viewAddSong:
    pattern:   /song/add
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewAdd } 

MyPlaylist_editSong:
    pattern:   /song/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Song:editSong }
    requirements:
        id:  \d+

MyPlaylist_viewEditSong:
    pattern:   /song/edit
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewEditSong }

MyPlaylist_viewDelSong:
    pattern:   /song/del
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewDelSong }

#PARTIE POUR LES ALBUMS
MyPlaylist_viewAlbum:
    pattern:   /album
    defaults:  { _controller: MyPlaylistAppBundle:Album:index }

MyPlaylist_viewAlbumId:
    pattern:   /album/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Album:ViewAlbum }
    requirements:
        id:  \d+

MyPlaylist_viewAddAlbum:
    pattern:   /album/add
    defaults:  { _controller: MyPlaylistAppBundle:Album:viewAdd } 

MyPlaylist_viewEditAlbum:
    pattern:   /album/edit
    defaults:  { _controller: MyPlaylistAppBundle:Album:viewEdit }

MyPlaylist_editAlbum:
    pattern:   /album/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Album:editAlbum }
    requirements:
        id:  \d+

MyPlaylist_viewDelAlbum:
    pattern:   /album/del
    defaults:  { _controller: MyPlaylistAppBundle:Album:viewDel }

    #PARTIE POUR LES TAGS
MyPlaylist_viewTag:
    pattern:   /tag
    defaults:  { _controller: MyPlaylistAppBundle:Tag:index }

MyPlaylist_viewTagId:
    pattern:   /tag/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Tag:ViewTag }
    requirements:
        id:  \d+

MyPlaylist_viewAddTag:
    pattern:   /tag/add
    defaults:  { _controller: MyPlaylistAppBundle:Tag:viewAdd } 

MyPlaylist_viewEditTag:
    pattern:   /tag/edit
    defaults:  { _controller: MyPlaylistAppBundle:Tag:viewEditTag }

MyPlaylist_editTag:
    pattern:   /tag/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Tag:editTag }
    requirements:
        id:  \d+

MyPlaylist_viewDelTag:
    pattern:   /tag/del
    defaults:  { _controller: MyPlaylistAppBundle:Tag:viewDel }

MyPlaylist_addTagToSong:
    pattern:   /tag/{idTag}/addToSong/{idSong}
    defaults:  { _controller: MyPlaylistAppBundle:Tag:addToSong }
    requirements:
        idSong:  \d+  
        idTag:  \d+  

MyPlaylist_delTagToSong:
    pattern:   /tag/{idTag}/delToSong/{idSong}
    defaults:  { _controller: MyPlaylistAppBundle:Tag:delToSong }
    requirements:
        idSong:  \d+  
        idPlaylist:  \d+      

        #PARTIE POUR LES BANDS
MyPlaylist_viewBand:
    pattern:   /band
    defaults:  { _controller: MyPlaylistAppBundle:Band:index }

MyPlaylist_viewBandid:
    pattern:   /band/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Band:ViewBand }
    requirements:
        id:  \d+

MyPlaylist_viewAddBand:
    pattern:   /band/add
    defaults:  { _controller: MyPlaylistAppBundle:Band:viewAdd } 

MyPlaylist_viewEditBand:
    pattern:   /band/edit
    defaults:  { _controller: MyPlaylistAppBundle:Band:viewEditBand }

MyPlaylist_editBand:
    pattern:   /band/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Band:editBand }
    requirements:
        id:  \d+

MyPlaylist_viewDelBand:
    pattern:   /band/del
    defaults:  { _controller: MyPlaylistAppBundle:Band:viewDel }