MyPlaylist_home:
    pattern:  /
    defaults: { _controller: MyPlaylistAppBundle:Home:index }

    
MyPlaylist_view:
    pattern:   /chanson/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Home:view }

MyPlaylist_search:
    pattern:   /search
    defaults:  { _controller: MyPlaylistAppBundle:Home:search }
    
MyPlaylist_add:
    pattern:   /add
    defaults:  { _controller: MyPlaylistAppBundle:Home:add }

MyPlaylist_edit:
    pattern:   /edit
    defaults:  { _controller: MyPlaylistAppBundle:Home:edit }

MyPlaylist_del:
    pattern:   /del
    defaults:  { _controller: MyPlaylistAppBundle:Home:del }

MyPlaylist_view_slug:
    pattern:   /{annee}/{slug}.{format}
    defaults:  { _controller: MyPlaylistAppBundle:Home:viewSlug, format: html }
    requirements:
        annee:  \d{4}
        format: html|xml

MyPlaylist_mail:
    pattern:   /mail
    defaults:  { _controller: MyPlaylistAppBundle:Home:mail }

MyPlaylist_about:
    pattern:   /about
    defaults:  { _controller: MyPlaylistAppBundle:Home:viewAbout }