#PARTIE POUR LE HOME
MyPlaylist_home:
    pattern:  /home
    defaults: { _controller: MyPlaylistAppBundle:Home:index }

MyPlaylist_search:
    pattern:   /home/search
    defaults:  { _controller: MyPlaylistAppBundle:Home:search }

MyPlaylist_mail:
    pattern:   /home/mail
    defaults:  { _controller: MyPlaylistAppBundle:Home:mail }

MyPlaylist_about:
    pattern:   /home/about
    defaults:  { _controller: MyPlaylistAppBundle:Home:viewAbout }


#PARTIE POUR LES PLAYLISTS
MyPlaylist_viewPlaylist:
    pattern:   /playlist
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:index }

MyPlaylist_viewPlaylistId:
    pattern:   /playlist/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewPlaylist }
    requirements:
        id:  \d+

MyPlaylist_viewDelPlaylist:
    pattern:   /playlist/del
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewDelPlaylist }

MyPlaylist_viewAddPlaylist:
    pattern:   /playlist/add
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewAdd }  

MyPlaylist_viewEditPlaylist:
    pattern:   /playlist/edit
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewEditPlaylist }

MyPlaylist_editPlaylist:
    pattern:   /playlist/edit/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:editPlaylist }
    requirements:
        id:  \d+

MyPlaylist_view_slugPlaylist:
    pattern:   /playlist/{annee}/{slug}.{format}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewSlug, format: html }
    requirements:
        annee:  \d4
        format: html|xml

#PARTIE POUR LES MUSIQUES
MyPlaylist_viewSong:
    pattern:   /song
    defaults:  { _controller: MyPlaylistAppBundle:Song:index }

MyPlaylist_viewSongId:
    pattern:   /song/view/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Song:ViewSong }
    requirements:
        id:  \d+

MyPlaylist_viewAddSong:
    pattern:   /song/add
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewAdd } 

MyPlaylist_viewEditSong:
    pattern:   /song/edit
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewEditSong }

MyPlaylist_viewDelSong:
    pattern:   /song/del
    defaults:  { _controller: MyPlaylistAppBundle:Song:viewDelSong }
