#PARTIE POUR LE HOME
MyPlaylist_home:
    pattern:  /home
    defaults: { _controller: MyPlaylistAppBundle:Home:index }

MyPlaylist_search:
    pattern:   /home/search
    defaults:  { _controller: MyPlaylistAppBundle:Home:search }

MyPlaylist_mail:
    pattern:   /home/mail
    defaults:  { _controller: MyPlaylistAppBundle:Home:mail }

MyPlaylist_about:
    pattern:   /home/about
    defaults:  { _controller: MyPlaylistAppBundle:Home:viewAbout }


#PARTIE POUR LES PLAYLISTS
MyPlaylist_viewPlaylist:
    pattern:   /playlist
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:index }

MyPlaylist_viewPlaylistId:
    pattern:   /playlist/{id}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewPlaylist }
    requirements:
        id:  \d{4}

MyPlaylist_addPlaylist:
    pattern:   /playlist/add/
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:add }

MyPlaylist_editPlaylist:
    pattern:   /playlist/edit
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:edit }
    requirements:
        id:  \d{4}

MyPlaylist_delPlaylist:
    pattern:   /playlist/del
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:del }
    requirements:
        id:  \d{4}

MyPlaylist_view_slugPlaylist:
    pattern:   /playlist/{annee}/{slug}.{format}
    defaults:  { _controller: MyPlaylistAppBundle:Playlist:viewSlug, format: html }
    requirements:
        annee:  \d{4}
        format: html|xml

#PARTIE POUR LES MUSIQUES
MyPlaylist_song:
    pattern:   /song
    defaults:  { _controller: MyPlaylistAppBundle:Song:index }

MyPlaylist_addSong:
    pattern:   /song/add
    defaults:  { _controller: MyPlaylistAppBundle:Song:add }

MyPlaylist_editSong:
    pattern:   /song/edit
    defaults:  { _controller: MyPlaylistAppBundle:Song:edit }

MyPlaylist_delSong:
    pattern:   /song/del
    defaults:  { _controller: MyPlaylistAppBundle:Song:del }
